### ISSUE TITLE
query.Cacheable(debugInfo) throws error

### ISSUE THREAD

**Issue by santubangalore** [VahidN/EFSecondLevelCache.Core#24]
# Summary of the issue
    I am faced with the  problem of query.Cacheable(debugInfo) thrwing error.

## Environment
    VS 2017 Pro, dot net core 2.0
```
The in-use version:
Operating system: 
IDE: (e.g. Visual Studio 2015): Visual tudio 2017, Dot net core 2.0
```

## Example code/Steps to reproduce:

   **I have created extension method ToCacheList<T> in a class. 

   next i am invoking the method with iqueryable object.
   
   var q = from c in this.Query() select c;

   return await q.ToCacheList<PaymentLeadTimeModel>();**

  
```
paste your core code
```
 public static async Task<IEnumerable<T>> ToCacheList<T>(this IQueryable<T> query)
        {
            EFCacheDebugInfo debugInfo = new EFCacheDebugInfo();
            var result = redisOn ?
                await query.Cacheable(debugInfo).ToListAsync() :
                await query.ToListAsync();
            return result;
        }
## Output:
    
```
Exception message:
System.InvalidOperationException: Unable to resolve service for type 'CacheManager.Core.ICacheManager`1[System.Object]' while attempting to activate 'EFSecondLevelCache.Core.EFCacheServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at EFSecondLevelCache.Core.EFCachedQueryExtensions.configureProviders()
```

**Comment by VahidN** [comment]
```
Unable to resolve service for type 'CacheManager.Core.ICacheManager`1[System.Object]'
```
means you have not registered the `ICacheManager` service. [follow this sample for more info](https://github.com/VahidN/EFSecondLevelCache.Core/blob/master/src/Tests/EFSecondLevelCache.Core.AspNetCoreSample/Startup.cs#L101).
