### ISSUE TITLE
Cannot cast EFCachedQueryable to IOrderedQueryable

### ISSUE THREAD

**Issue by Rayvid** [VahidN/EFSecondLevelCache.Core#42]
# Summary of the issue
Message: System.InvalidCastException : Unable to cast object of type 'EFSecondLevelCache.Core.EFCachedQueryable`1[Whatever.Model.PricingEntities.PriceCalculationParameter]' to type 'System.Linq.IOrderedQueryable`1[Whatever.Model.PricingEntities.PriceCalculationParameter]'.

## Environment
All

## Example code/Steps to reproduce:

            var priceCalculationParameters = await pricingContext.PriceCalculationParameters.Cacheable()
                .Where(x => x.PricingId == currentPricing.PricingId)
                .OrderBy(x => x.PriceValidityIntervals.Min(y => y.Start))
                .ToListAsync().ConfigureAwait(false);

## Output:

Test Name:	CalculateRoughReservedEndTime_WithReservedAmountAndStartingWithinPaidTimeInterval_ShouldReturnTheSameEndTime(Monday)
Test FullName:	Whatever.Backend.Tests.Service.PriceCalculationServiceTests.CalculateRoughReservedEndTime_WithReservedAmountAndStartingWithinPaidTimeInterval_ShouldReturnTheSameEndTime(Monday)
Test Source:	C:\Users\gkisonas\Projects\Whatever\Whatever.Backend.Tests\Service\PriceCalculationServiceTests.cs : line 2824
Test Outcome:	Failed
Test Duration:	0:00:07.111

Result StackTrace:	
at System.Linq.Queryable.OrderBy[TSource,TKey](IQueryable`1 source, Expression`1 keySelector)
   at Whatever.Backend.Services.PriceCalculationService.<CalculateRoughReservedEndTime>d__46.MoveNext() in C:\Users\gkisonas\Projects\Whatever\Whatever.Backend\Services\PriceCalculationService.cs:line 934
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Whatever.Backend.Tests.Service.PriceCalculationServiceTests.<CalculateRoughReservedEndTime_WithReservedAmountAndStartingWithinPaidTimeInterval_ShouldReturnTheSameEndTime>d__71.MoveNext() in C:\Users\gkisonas\Projects\Whatever\Whatever.Backend.Tests\Service\PriceCalculationServiceTests.cs:line 2841
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)
Result Message:	System.InvalidCastException : Unable to cast object of type 'EFSecondLevelCache.Core.EFCachedQueryable`1[Whatever.Model.PricingEntities.PriceCalculationParameter]' to type 'System.Linq.IOrderedQueryable`1[Whatever.Model.PricingEntities.PriceCalculationParameter]'.

**Comment by VahidN** [comment]
Which version? Have you tried adding the `Cacheable()` method before the `ToListAsync()` method?

**Comment by Rayvid** [comment]
Cacheable after OrderBy works, thanks. So in general pattern is to put Cacheable after last IQueryable? What will be cached then, only filtered data got to this point? Or statement works like key - cache will work only for same statement?

**Comment by VahidN** [comment]
yes, yes, yes!
